language: node_js

sudo: required

services:
  - docker

env:
  global:
    - OPENCV4NODEJS_DISABLE_AUTOBUILD=1
    - LATEST_STABLE_NODEJS_VERSION=12
    - OPENCV3_LATEST=3.4.6
    - OPENCV4_LATEST=4.1.0

matrix:
  include:
    # latest OpenCV 4
    - os: linux
      node_js: 6
      env:
        - OPENCV_VERSION=$OPENCV4_LATEST-contrib
          BUILD_TASK=test
    - os: linux
      node_js: 6
      env:
        - OPENCV_VERSION=$OPENCV4_LATEST-contrib
          BUILD_TASK=prebuild
    - os: linux
      node_js: 8
      env:
        - OPENCV_VERSION=$OPENCV4_LATEST-contrib
          BUILD_TASK=test
    - os: linux
      node_js: 8
      env:
        - OPENCV_VERSION=$OPENCV4_LATEST-contrib
          BUILD_TASK=prebuild
    - os: linux
      node_js: 10
      env:
        - OPENCV_VERSION=$OPENCV4_LATEST-contrib
          BUILD_TASK=test
    - os: linux
      node_js: 10
      env:
        - OPENCV_VERSION=$OPENCV4_LATEST-contrib
          BUILD_TASK=prebuild
    - os: linux
      node_js: 11
      env:
        - OPENCV_VERSION=$OPENCV4_LATEST-contrib
          BUILD_TASK=test
    - os: linux
      node_js: 11
      env:
        - OPENCV_VERSION=$OPENCV4_LATEST-contrib
          BUILD_TASK=prebuild
    - os: linux
      node_js: $LATEST_STABLE_NODEJS_VERSION
      env:
        - OPENCV_VERSION=$OPENCV4_LATEST-contrib
          BUILD_TASK=test
    - os: linux
      node_js: $LATEST_STABLE_NODEJS_VERSION
      env:
        - OPENCV_VERSION=$OPENCV4_LATEST-contrib
          BUILD_TASK=prebuild

    # code coverage
    - os: linux
      node_js: $LATEST_STABLE_NODEJS_VERSION
      env:
        - OPENCV_VERSION=$OPENCV4_LATEST-contrib
          BUILD_TASK=cover

    # osx opencv@4
    - os: osx
      node_js: 6
      env:
        - OPENCV_VERSION=4
          BUILD_TASK=test
    - os: osx
      node_js: 6
      env:
        - OPENCV_VERSION=4
          BUILD_TASK=prebuild
    - os: osx
      node_js: 8
      env:
        - OPENCV_VERSION=4
          BUILD_TASK=test
    - os: osx
      node_js: 8
      env:
        - OPENCV_VERSION=4
          BUILD_TASK=prebuild
    - os: osx
      node_js: 10
      env:
        - OPENCV_VERSION=4
          BUILD_TASK=test
    - os: osx
      node_js: 10
      env:
        - OPENCV_VERSION=4
          BUILD_TASK=prebuild
    - os: osx
      node_js: 11
      env:
        - OPENCV_VERSION=4
          BUILD_TASK=test
    - os: osx
      node_js: 11
      env:
        - OPENCV_VERSION=4
          BUILD_TASK=prebuild
    - os: osx
      node_js: $LATEST_STABLE_NODEJS_VERSION
      env:
        - OPENCV_VERSION=4
          BUILD_TASK=test
    - os: osx
      node_js: $LATEST_STABLE_NODEJS_VERSION
      env:
        - OPENCV_VERSION=4
          BUILD_TASK=prebuild

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    chmod +x ./ci/$BUILD_TASK/$BUILD_TASK.sh;
    fi

install: true

script:
  - if [[ $BUILD_TASK != "prebuild" && "$TRAVIS_OS_NAME" == "linux" ]]; then
    cd ./ci/$BUILD_TASK;
    npm run $BUILD_TASK $OPENCV_VERSION $TRAVIS_NODE_VERSION;
    fi
  - if [[ $BUILD_TASK != "prebuild" && "$TRAVIS_OS_NAME" == "osx" ]]; then
    sh ./ci/test/script/run-test.sh;
    fi
  - if [[ $BUILD_TASK == "prebuild" && $TRAVIS_TAG != "" ]]; then
    cd ./ci/$BUILD_TASK;
    npm run $BUILD_TASK $OPENCV_VERSION $TRAVIS_NODE_VERSION;
    fi

after_success:
  - if [ $BUILD_TASK = 'cover' ]; then
    npm install;
    npm run codecov -- -t $CODECOV_TOKEN;
    fi
