name: Run CI
on:
  push:
    branches-ignore:
      - develop
      - release/**
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        node: [ 12, 14 ]
        task: [ test ]

    runs-on: ${{matrix.os}}
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node}}
      - name: Run tests
        run: ./ci/test/script/run-test.sh;