name: Create tagged release
on:
  push:
    tags:
      - v*.*.*

jobs:
  prebuild-node:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-2019]
        node: [16]
        task: [prebuild]
        runtime: [node]
        target: ["16.0.0", "18.0.0"]
    runs-on: ${{matrix.os}}
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node}}
      - name: Configure msvs version on Windows
        if: ${{matrix.os == 'windows-2019'}}
        run: npm config set msvs_version 2019
      - name: Install
        run: npm ci --unsafe-perm
      - name: Publish prebuild
        shell: bash
        run: npm run prebuild -- -t ${{matrix.target}} -r ${{matrix.runtime}} -u ${{ secrets.GH_TOKEN }} --verbose

  deploy:
    needs:
      - prebuild-node
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Publish tagged release
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: public
